---
- hosts: database
  tasks:
    - name: install mysql-server and mysql_db dependencies
      apt: name={{ item }} state=present update_cache=yes
      loop:
        - mysql-server
        - python-mysqldb

    - name: ensure mysql started
      service: name=mysql state=started enabled=yes

  ##Note: ansible -m setup <hostname>  (to gather facts)
    # - name: ensure mysql listening on all ports
    #   lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = {{ ansible_eth0.ipv4.address }}"
    #   notify: restart mysql

    - name: ensure mysql listening on all ports
      lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql

    - name: create database
      mysql_db: name=demo state=present

      ##Note: demo.*:ALL - database.table:priv1,priv2
    - name: create user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='localhost' state=present

  handlers:
    - name: restart mysql
      service: name=mysql state=restarted
